stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Build stage running"

test-job:
  stage: test
  script:
    - echo "Test stage running"

deploy-job:
  stage: deploy
  script:
    - echo "Deploy stage running"